name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
      - name: configure brew running environment
        run: |
          brew update-reset
          brew tap nnstreamer/neural-network
          brew update
      - name: build formula from source
        run: |
          brew install --build-from-source ./Formula/nnstreamer.rb -v
