name: CI
on:
  pull_request_target:

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: configure brew running environment
        run: |
          brew update-reset
          brew tap nnstreamer/neural-network
          brew update
      - name: build formula from source
        run: |
          brew install --build-from-source ./Formula/nnstreamer.rb -v
